basePath: /api/v1
host: localhost:5000
info:
  title: Physiotherapy platform backend api doc
  version: 1.0.0
paths:
  /accesstest: {}
  /login:
    post:
      parameters:
      - in: body
        name: parameters
        required: true
        schema:
          properties:
            email:
              type: string
            password:
              type: string
            remember_login:
              type: boolean
          required:
          - email
          - password
          - remember_login
          type: object
      responses:
        '400':
          description: missing fields
        '401':
          description: Wrong username or password
      tags:
      - Login
  /logout: {}
  /patient/link:
    get:
      parameters: []
      responses:
        '200':
          description: typing.List[backend.routes.TokenObject]
        '400':
          description: missing fields
        '403':
          description: Only patients are allowed to access this resource
      tags:
      - PatientLinking
    post:
      parameters:
      - in: body
        name: parameters
        required: true
        schema:
          properties:
            accept:
              type: boolean
            professional_token:
              type: string
          required:
          - professional_token
          - accept
          type: object
      responses:
        '200':
          description: Invite updated
        '400':
          description: missing fields
        '403':
          description: Only patients are allowed to access this resource
        '404':
          description: Professional not found
        '409':
          description: Professional already linked
      tags:
      - PatientLinking
  /patient/sessions:
    get:
      parameters: []
      responses:
        '200':
          description: typing.Dict[str, typing.List[typing.Dict[str, int]]]
        '400':
          description: missing fields
        '403':
          description: Only patients are allowed to access this resource
      tags:
      - PatientSessions
  /patient/signup:
    post:
      parameters:
      - in: body
        name: parameters
        required: true
        schema:
          properties:
            cpf:
              type: string
            email:
              type: string
            name:
              type: string
            password:
              type: string
            remember_login:
              type: boolean
          required:
          - email
          - name
          - password
          - cpf
          - remember_login
          type: object
      responses:
        '400':
          description: missing fields
        '406':
          description: Password too short. Minimum 8 characters long
        '409':
          description: Email already in use
      tags:
      - PatientSignup
  /professional/link:
    get:
      parameters: []
      responses:
        '200':
          description: typing.List[backend.routes.TokenObject]
        '400':
          description: missing fields
        '403':
          description: Only professionals are allowed to access this resource
      tags:
      - ProfessionalLinking
    post:
      parameters:
      - in: body
        name: parameters
        required: true
        schema:
          properties:
            cpf:
              type: string
          required:
          - cpf
          type: object
      responses:
        '200':
          description: Invite created
        '400':
          description: missing fields
        '403':
          description: Only professionals are allowed to access this resource
        '404':
          description: Patient not found
        '409':
          description: Invite already exists
      tags:
      - ProfessionalLinking
  /professional/sessions:
    get:
      parameters:
      - in: query
        name: patient_token
        required: true
        type: string
      responses:
        '200':
          description: typing.Dict[str, typing.List[typing.Dict[str, int]]]
        '400':
          description: missing fields
        '403':
          description: Only professionals are allowed to access this resource
        '404':
          description: Patient not found
      tags:
      - ProfessionalPatientSessions
  /professional/signup:
    post:
      parameters:
      - in: body
        name: parameters
        required: true
        schema:
          properties:
            cpf:
              type: string
            email:
              type: string
            institution:
              type: string
            name:
              type: string
            password:
              type: string
            registration_id:
              type: string
            remember_login:
              type: boolean
          required:
          - email
          - name
          - password
          - cpf
          - registration_id
          - institution
          - remember_login
          type: object
      responses:
        '400':
          description: missing fields
        '406':
          description: Password too short. Minimum 8 characters long
        '409':
          description: Email already in use
      tags:
      - ProfessionalSignup
  /video:
    get:
      parameters:
      - in: query
        name: video_id
        required: true
        type: integer
      responses:
        '400':
          description: missing fields
        '404':
          description: Video not found
      tags:
      - Video
schemes:
- https
- http
swagger: '2.0'
tags:
- name: PatientSignup
- name: ProfessionalSignup
- name: Login
- name: Logout
- name: ProfessionalLinking
- name: ProfessionalPatientSessions
- name: PatientLinking
- name: PatientSessions
- name: Video
- name: AccessTest
